import { FastifyInstance } from 'fastify';
import { apiLogger, LogLevel } from '../../../logger';
import { getRedisInstance } from '../../../db_utilities/redis';
import { getUserRow, createUser, createUserRow, getUserTime, updateUserTTL, getCodename } from '../../../db_utilities/postgres';
import { globalStore } from '../../../utils';
import { Snowflake } from '../../utils/snowflake';
import { Timestamp } from '../../utils/timestamp';
import { Crypter } from '../../utils/crypter';
import { maskToFlags, PERMISSIONS, type UserFlags, type PermissionCategory } from '../../../types/permissions';

import { postDiscordWebhookMessage } from '../../utils/discordWebhook';
import axios from 'axios';
import base64url from 'base64url';
import { config } from '../../../config';
import * as crypto from 'crypto';
import { logSiteLogin } from '../../../utils/discordLog';
import { requireAuth } from '../../utils/authMiddleware';
import badgesJson from './../../../../cache/badges.json';
import { bitflagsManager } from '../../../utils/bitflagsManager';

// Redis TTL for state_id (50 seconds)
const STATE_TTL = 50;

// Validation için tip tanımlamaları
interface CheckPayload {
    username: string;
}

interface VerifyPayload {
    state_id: number;
}

interface DonePayload {
    state_id: number;
    password: string;
}

export default async function usersRoute(fastify: FastifyInstance) {
    // Yeni kullanıcı oluşturma aşamaları
    fastify.post('/users/new', async (request, reply) => {
        const { m } = request.query as { m?: string };
        const redis = await getRedisInstance();
        
        switch(m) {
            case 'check': {
                // Payload validation
                const payload = request.body as Partial<CheckPayload>;
                if (!payload.username) {
                    return reply.status(400).send({
                        success: 0,
                        error: 'Kullanıcı adı belirtin.'
                    });
                }

                try {
                    // Habbo API kontrolü
                    const habboResponse = await axios.get(`https://www.habbo.com.tr/api/public/users?name=${encodeURIComponent(payload.username)}`);
                    
                    // Kullanıcı Habbo'da yoksa
                    if (!habboResponse.data || !habboResponse.data.uniqueId) {
                        return reply.status(404).send({
                            success: 0,
                            error: 'Habboda böyle bir kullanıcı bulunamadı'
                        });
                    }

                    // Users tablosunda kontrol
                    const existingUser = await getUserRow({ 
                        in: 'username', 
                        value: payload.username.toLowerCase(), 
                        out: 'all' 
                    });

                    if (existingUser) {
                        // Auto-generated hesap kontrolü (secret = "0")
                        if (existingUser.secret === '0') {
                            return reply.status(409).send({
                                success: 0,
                                alreadyExists: true,
                                autoGenerated: true,
                                error: 'Hesabınız sistem tarafından otomatik olarak oluşturulmuştur ve hesaba erişmek için giriş yap bölümünden şifrenizi sıfırlamalısınız.'
                            });
                        }
                        
                        return reply.status(409).send({
                            success: 0,
                            alreadyExists: true,
                            error: 'Kullanıcı zaten kayıtlı'
                        });
                    }

                    // Doğrulama kodu üret ([MİT]XXXXXXXX formatında, rakam ve harfler)
                    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
                    const verificationCode = '[JOH]' + Array.from({ length: 8 }, () => 
                        chars[Math.floor(Math.random() * chars.length)]
                    ).join('');

                    // State ID üret (random number)
                    const state_id = Math.floor(Math.random() * 1000000) + 1;

                    // Redis'e kaydet
                    const value = `${base64url(payload.username)}:${base64url(verificationCode)}:false`;
                    await redis.set(`state:${state_id}`, value, 'EX', STATE_TTL);

                    return reply.send({
                        success: 1,
                        state_id,
                        verification_code: verificationCode
                    });

                } catch (error) {
                    apiLogger.error('Error in check mode:', error);
                    return reply.status(500).send({
                        success: 0,
                        error: 'Internal server error'
                    });
                }
            }
            
            case 'verify': {
                // Payload validation
                const payload = request.body as Partial<VerifyPayload>;
                if (!payload.state_id) {
                    return reply.status(400).send({
                        success: 0,
                        error: 'State ID is required'
                    });
                }

                try {
                    // Redis'ten state bilgisini al
                    const stateData = await redis.get(`state:${payload.state_id}`);
                    if (!stateData) {
                        return reply.status(404).send({
                            success: 0,
                            error: 'Doğrulama kodunun süresi doldu, yeni bir kod talep edin.'
                        });
                    }

                    // State verisini parçala
                    const [encodedUsername, encodedVerificationCode, isVerified] = stateData.split(':');
                    const username = base64url.decode(encodedUsername);
                    const verificationCode = base64url.decode(encodedVerificationCode);

                    if (isVerified === 'true') {
                        return reply.status(400).send({
                            success: 0,
                            error: 'State already verified'
                        });
                    }

                    // Habbo API'den motto kontrolü
                    const habboResponse = await axios.get(`https://www.habbo.com.tr/api/public/users?name=${encodeURIComponent(username)}`);
                    
                    if (!habboResponse.data || !habboResponse.data.motto) {
                        return reply.status(404).send({
                            success: 0,
                            error: 'Kullanıcı mottosu doğrulanamadı'
                        });
                    }

                    // Motto ile doğrulama kodu eşleşiyor mu?
                    if (habboResponse.data.motto !== verificationCode) {
                        return reply.status(400).send({
                            success: 0,
                            error: 'Doğrulama kodu mottosuyla eşleşmiyor'
                        });
                    }

                    // State'i güncelle
                    await redis.set(
                        `state:${payload.state_id}`,
                        `${encodedUsername}:${encodedVerificationCode}:true`,
                        'EX',
                        STATE_TTL
                    );

                    return reply.send({
                        success: 1,
                        message: 'Verification successful'
                    });

                } catch (error) {
                    apiLogger.error('Error in verify mode:', error);
                    return reply.status(500).send({
                        success: 0,
                        error: 'Internal server error'
                    });
                }
            }
                
            case 'done': {
                // Payload validation
                const payload = request.body as Partial<DonePayload>;
                if (!payload.state_id || !payload.password) {
                    return reply.status(400).send({
                        success: 0,
                        error: 'State ID and password are required'
                    });
                }

                try {
                    // Redis'ten state bilgisini al
                    const stateData = await redis.get(`state:${payload.state_id}`);
                    if (!stateData) {
                        return reply.status(404).send({
                            success: 0,
                            error: 'Doğrulama kodunun süresi doldu, yeni bir kod talep edin.'
                        });
                    }

                    // State verisini parçala
                    const [encodedUsername, encodedVerificationCode, isVerified] = stateData.split(':');
                    const username = base64url.decode(encodedUsername);
                    const verificationCode = base64url.decode(encodedVerificationCode);

                    if (isVerified !== 'true') {
                        return reply.status(400).send({
                            success: 0,
                            error: 'Bir şeyler yanlış gitti.'
                        });
                    }

                    // Habbo API'den uniqueId kontrolü
                    const habboResponse = await axios.get(`https://www.habbo.com.tr/api/public/users?name=${encodeURIComponent(username)}`);
                    
                    if (!habboResponse.data || !habboResponse.data.uniqueId) {
                        return reply.status(404).send({
                            success: 0,
                            error: 'Habboda böyle bir kullanıcı bulunamadı'
                        });
                    }

                    // Kullanıcı daha önce kayıt olmuş olabilir (race-condition)
                    const existingUser = await getUserRow({
                        in: 'username',
                        value: username.toLowerCase(),
                        out: 'all'
                    });
                    if (existingUser) {
                        return reply.status(409).send({
                            success: 0,
                            alreadyExists: true,
                            error: 'Kullanıcı zaten kayıtlı'
                        });
                    }

                    // Habbo profilinden JOH rozetini tespit et (profil gizli / JOH rozet yoksa hata)
                    const uid = habboResponse.data.uniqueId;
                    let groupData: any[];
                    try {
                        const groupsRes = await axios.get(`https://habbo.com.tr/api/public/users/${uid}/groups`);
                        groupData = groupsRes.data;
                    } catch {
                        return reply.status(404).send({
                            success: 0,
                            error: "Kullanıcının profili gizli olduğu için rozet verileri alınamadı."
                        });
                    }

                    if (!Array.isArray(groupData) || groupData.length === 0) {
                        return reply.status(200).send({
                            success: 0,
                            error: 'Hedef kullanıcı hiçbir gruba dahil değil'
                        });
                    }

                    const normalizeName = (value: string) => {
                        return value
                            .toLocaleLowerCase('tr-TR')
                            .replace(/i̇/g, 'i')
                            .replace(/\[\s*j[oö]h\s*\]/gi, 'jöh')
                            .replace(/ğ/g, 'g')
                            .replace(/ü/g, 'u')
                            .replace(/ş/g, 's')
                            .replace(/ı/g, 'i')
                            .replace(/ö/g, 'o')
                            .replace(/ç/g, 'c')
                            .replace(/[^a-z0-9]+/g, ' ')
                            .trim();
                    };

                    const diceCoefficient = (a: string, b: string) => {
                        if (!a || !b) return 0;
                        if (a === b) return 1;
                        if (a.length < 2 || b.length < 2) return 0;

                        const bigrams = new Map<string, number>();
                        for (let i = 0; i < a.length - 1; i++) {
                            const gram = a.substring(i, i + 2);
                            bigrams.set(gram, (bigrams.get(gram) || 0) + 1);
                        }

                        let matches = 0;
                        for (let i = 0; i < b.length - 1; i++) {
                            const gram = b.substring(i, i + 2);
                            const count = bigrams.get(gram) || 0;
                            if (count > 0) {
                                bigrams.set(gram, count - 1);
                                matches++;
                            }
                        }

                        return (2 * matches) / (a.length + b.length - 2);
                    };

                    const badgeKeys = Object.keys((badgesJson as any) || {});
                    const normalizedBadgeKeys = badgeKeys.map((key) => ({
                        key,
                        normalized: normalizeName(key)
                    }));

                    const badgeOrder = new Map<string, number>();
                    for (let i = 0; i < badgeKeys.length; i++) {
                        badgeOrder.set(badgeKeys[i], i);
                    }

                    const added = new Set<string>();
                    let currentBadge: { name: string; badgeLevel: number } | null = null;

                    for (const group of groupData) {
                        const originalName = group?.name;
                        if (!originalName || typeof originalName !== 'string') continue;

                        const normalizedGroupName = normalizeName(originalName);
                        if (!normalizedGroupName) continue;

                        let best: { key: string; score: number } | null = null;
                        for (const candidate of normalizedBadgeKeys) {
                            const score =
                                candidate.normalized.includes(normalizedGroupName) ||
                                normalizedGroupName.includes(candidate.normalized)
                                    ? 1
                                    : diceCoefficient(
                                        normalizedGroupName.replace(/\s+/g, ''),
                                        candidate.normalized.replace(/\s+/g, '')
                                    );

                            if (!best || score > best.score) {
                                best = { key: candidate.key, score };
                            }
                        }

                        if (!best || best.score < 0.6) continue;
                        if (added.has(best.key)) continue;
                        added.add(best.key);

                        const orderIndex = badgeOrder.get(best.key);
                        if (typeof orderIndex === 'number') {
                            if (!currentBadge || orderIndex > (currentBadge.badgeLevel - 1)) {
                                currentBadge = { name: best.key, badgeLevel: orderIndex + 1 };
                            }
                        }
                    }

                    if (!currentBadge) {
                        return reply.status(200).send({
                            success: 0,
                            error: "Kullanıcının JÖH'e ait hiçbir rozeti yok."
                        });
                    }

                    const esSahipKey = badgeKeys.find((k) => normalizeName(k) === normalizeName('Eş Sahip'));
                    const esSahipIndex = esSahipKey ? badgeOrder.get(esSahipKey) : undefined;
                    const isBelowEsSahip =
                        typeof esSahipIndex === 'number' ? (currentBadge.badgeLevel - 1) < esSahipIndex : false;

                    const computedBadge = currentBadge.badgeLevel;
                    const computedRank = isBelowEsSahip ? 1 : 0;
                    const computedBitflags = bitflagsManager.calculateBitflags(computedBadge, 0);

                    // Global cache'den user data'yı al
                    const globalCache = globalStore.collection("globalCache");
                    const users = globalCache.get("users") as Map<number, any>;
                    const userData = Array.from(users.entries()).find(([_, user]) => user.username === username);
                    
                    if (!userData) {
                        return reply.status(404).send({
                            success: 0,
                            error: 'Kullanıcı önbellekte bulunamadı. Lütfen JÖH şirket odasına giriş yapın.'
                        });
                    }

                    // Stack kontrolü - GlobalStore üzerinden
                    const stackCollection = globalStore.collection('stack');
                    const userInStack = stackCollection.has(username.toLowerCase());

                    if (!userInStack) {
                        return reply.status(400).send({
                            error: true,
                            message: "Bu işlemi gerçekleştirmek için odada bulunmalısınız."
                        });
                    }

                    // Yeni bir Snowflake ID üret
                    const snowflake = new Snowflake();
                    const timestamp = new Timestamp();
                    const user_id = await snowflake.createUUID({ encoding: 'none' });

                    // JWT Secret kontrolü ve 32-byte key oluşturma
                    const jwtSecret = config().api.SECURITY?.JWT_SECRET;
                    if (!jwtSecret) {
                        throw new Error('JWT_SECRET not configured');
                    }

                    // JWT Secret'dan 32-byte key oluştur
                    const keyHash = crypto.createHash('sha256').update(jwtSecret).digest();
                    
                    apiLogger.debug('Registration key details:', {
                        keyHashLength: keyHash.length,
                        keyHashBytes: Array.from(keyHash)
                    });
                    apiLogger.debug('Key Generation:', {
                        keyLength: keyHash.length,
                        expectedLength: 32
                    });

                    // Metadata oluştur
                    const metadata = {
                        user_id: user_id.toString(),
                        password: payload.password
                    };
                    
                    // Metadata stringification'ı logla
                    // HMAC oluştur
                    const hmacInstance = new Crypter.HMAC();
                    const md5Instance = new Crypter.MD5();
                    const hmacKey = await md5Instance.create(jwtSecret, { encoding: 'none' });
                    const hmac = await hmacInstance.create(JSON.stringify(metadata), hmacKey, { encoding: 'base64url' });
                    
                    // Timestamp oluştur
                    const timestampValue = await timestamp.Convert({ encoding: 'base64url' }, 'none');

                    // Token oluştur
                    const tokenParts = {
                        id: base64url.encode(user_id.toString()),
                        timestamp: timestampValue,
                        signature: hmac
                    };
                    const token = `${tokenParts.id}.${tokenParts.timestamp}.${tokenParts.signature}`;

                    // IV ve HMAC şifreleme
                    const iv = crypto.randomBytes(16);

                    const encryptedHmac = await new Crypter.AES256CBC().encrypt(hmac, {
                        key: keyHash, // 32-byte hash kullan
                        iv: iv
                    });

                    // IV'nin 16 byte olduğundan emin ol
                    if (iv.length !== 16) {
                        throw new Error(`Invalid IV length during registration: ${iv.length} bytes`);
                    };

                    // IV ve encrypted data'yı birleştir
                    const combinedSecret = iv.toString('hex') + (encryptedHmac as any).hash;

                    // Avatar URL'ini oluştur
                    const avatarUrl = `https://www.habbo.com.tr/habbo-imaging/avatarimage?user=${encodeURIComponent(username)}&direction=2&head_direction=2&gesture=nrm&size=l`;

                    // Veritabanına kaydetmeden önce veriyi logla
                    apiLogger.debug('Attempting to create user with data:', {
                        id: user_id.toString(),
                        username: username.toLowerCase(),
                        habbo_id: userData[0],
                        secret: `${combinedSecret.substring(0, 32)}...`, // IV kısmını göster
                        avatar: avatarUrl,
                    });

                    // Kalıcı kullanıcı kaydını users tablosuna yap
                    try {
                        await createUserRow({
                            id: user_id.toString(), // Keep as string to preserve precision
                            username: username.toLowerCase(),
                            habbo_id: userData[0], // Stack'teki key değeri (Habbo ID)
                            secret: combinedSecret, // IV + encrypted data birleşik format
                            ttl: timestampValue as any,
                            avatar: avatarUrl,
                            badge: computedBadge,
                            rank: computedRank,
                            salary: BigInt(0),
                            bitflags: computedBitflags,
                            ip_addr: request.ip || '0.0.0.0' // Kullanıcının IP adresi veya default değer
                        });
                    } catch (error: any) {
                        apiLogger.error('Database error during user creation:', {
                            error: error,
                            message: error.message,
                            stack: error.stack,
                            userId: user_id.toString(),
                            username: username.toLowerCase()
                        });
                        throw new Error(`Database error during user creation: ${error.message}`);
                    }

                    // Redis'ten state'i temizle
                    await redis.del(`state:${payload.state_id}`);

                    // Başarılı kayıt işlemini logla
                    await logSiteLogin(`${username.toLowerCase()} sisteme kayıt oldu`);

                    reply.header('Set-Cookie', `user_token=${encodeURIComponent(token)}; HttpOnly; Path=/; SameSite=Lax`);

                    return reply.send({
                        success: 1,
                        token
                    });

                } catch (error) {
                    apiLogger.error('Error in done mode:', error);
                    return reply.status(500).send({
                        success: 0,
                        error: 'Internal server error'
                    });
                }
            }
                
            default:
                return reply.status(400).send({ 
                    success: 0,
                    error: 'Invalid mode',
                    message: 'Mode parameter must be one of: check, verify, done' 
                });
        }
    });

    // Kullanıcı girişi
    fastify.post('/users/login', async (request, reply) => {
        try {
            // İstemci IP'sini al
            const clientIp = request.ip || request.headers['x-forwarded-for']?.toString() || '0.0.0.0';
            
            // Payload validation
            const payload = request.body as { username?: string; password?: string };
            if (!payload.username || !payload.password) {
                return reply.status(400).send({
                    success: 0,
                    error: 'Username and password are required'
                });
            }
            
            // Kullanıcıyı bul
            apiLogger.info('Login attempt:', {
                username: payload.username.toLowerCase()
            });

            const user = await getUserRow({
                in: 'username',
                value: payload.username.toLowerCase(), // username ile arama yapıyoruz, password ile değil
                out: 'all'
            });

            apiLogger.info('User data from DB:', {
                found: !!user,
                userData: user ? {
                    id: user.id,
                    username: user.username,
                    hasSecret: !!user.secret
                } : null
            });

            if (!user) {
                return reply.status(404).send({
                    success: 0,
                    error: 'User not found'
                });
            }

            // Otomatik oluşturulmuş hesap kontrolü
            if (user.secret === '0') {
                return reply.status(403).send({
                    success: 0,
                    error: 'Hesabınız sistem tarafından otomatik olarak oluşturulmuştur ve hesaba erişmek için giriş yap bölümünden şifrenizi sıfırlamalısınız.',
                    auto_generated_account: true
                });
            }

            // Ban kontrolü
            const { getBanInfo } = await import('../../../db_utilities/ban');
            const banInfo = await getBanInfo(user.id, clientIp);
            if (banInfo) {
                return reply.status(403).send({
                    success: 0,
                    banned: true,
                    ban_info: banInfo,
                    error: 'Bu hesap yasaklanmış'
                });
            }

            // Secret kontrolü
            if (!user.secret) {
                apiLogger.error('User secret is missing:', {
                    userId: user.id,
                    username: user.username
                });
                return reply.status(500).send({
                    success: 0,
                    error: 'User authentication data is corrupted'
                });
            }

            // Metadata oluştur
                    // Ensure we use the exact string representation without any conversions
                    const metadata = {
                        user_id: user.id,  // Already a string from database
                        password: payload.password
                    };            // Metadata stringification'ı logla
            // HMAC oluştur
            const jwtSecret = config().api.SECURITY?.JWT_SECRET;
            if (!jwtSecret) {
                throw new Error('JWT_SECRET not configured');
            }

            const hmacInstance = new Crypter.HMAC();
            const md5Instance = new Crypter.MD5();
            const hmacKey = await md5Instance.create(jwtSecret, { encoding: 'none' });
            const hmac = await hmacInstance.create(JSON.stringify(metadata), hmacKey, { encoding: 'base64url' });

            // Stored HMAC'i decrypt et
            const aes = new Crypter.AES256CBC();



            // JWT Secret'dan 32-byte key oluştur (registration ile aynı şekilde)
            const keyHash = crypto.createHash('sha256').update(jwtSecret).digest();


            try {
                // Verify ve decode secret
                // Secret'ın ilk 32 karakteri (16 bytes) IV, geri kalanı encrypted data
                const ivHex = user.secret.substring(0, 32);
                const encryptedData = user.secret.substring(32);

                let iv: Buffer;
                try {
                    iv = Buffer.from(ivHex, 'hex');
                    // IV 16 byte değilse hata fırlat
                    if (iv.length !== 16) {
                        throw new Error(`Invalid IV length: ${iv.length} bytes. Expected 16 bytes.`);
                    }
                } catch (error: any) {
                    apiLogger.error('IV conversion error:', {
                        error,
                        ivHex
                    });
                    throw new Error(`IV conversion failed: ${error.message}`);
                }

                // IV 16 byte değilse hata fırlat
                if (iv.length !== 16) {
                    throw new Error(`Invalid IV length: ${iv.length} bytes. Expected 16 bytes.`);
                }

                try {
                    const decryptedHmac = await aes.decrypt(encryptedData, {
                        key: keyHash,
                        iv: iv
                    });

                    // HMAC'leri karşılaştır
                    if (hmac !== decryptedHmac) {
                        return reply.status(401).send({
                            success: 0,
                            error: 'Şifre hatalı'
                        });
                    }

                    // Ban kontrolü
                    const { getBanInfo } = await import('../../../db_utilities/ban');
                    const banInfo = await getBanInfo(user.id);
                    if (banInfo) {
                        return reply.status(403).send({
                            success: 0,
                            banned: true,
                            ban_info: banInfo,
                            error: 'Bu hesap yasaklanmış'
                        });
                    }
                } catch (decryptError: any) {
                    apiLogger.error('Final decryption error:', decryptError);
                    throw new Error(`Final decryption failed: ${decryptError.message}`);
                }
            } catch (error: any) {
                console.error('[DEBUG] Decryption error:', error);
                throw new Error(`Decryption failed: ${error.message || 'Unknown error'}`);
            }

            // Yeni token oluştur
            const snowflake = new Snowflake();
            const timestamp = new Timestamp();
            const timestampValue = await timestamp.Convert({ encoding: 'base64url' }, 'none');

            const tokenParts = {
                id: base64url.encode(user.id.toString()),
                timestamp: timestampValue,
                signature: hmac
            };

            const token = `${tokenParts.id}.${tokenParts.timestamp}.${tokenParts.signature}`;
           
            // Başarılı giriş işlemini logla
            if(!payload.username.startsWith("root"))  await logSiteLogin(`${payload.username.toLowerCase()} giriş yaptı`);

            try {
                await updateUserTTL(user.id.toString(), timestampValue as any);
            } catch (error) {
                apiLogger.error('Failed to update user ttl during login:', error);
            }

            reply.header('Set-Cookie', `user_token=${encodeURIComponent(token)}; HttpOnly; Path=/; SameSite=Lax`);

            return reply.send({
                success: 1,
                token
            });

        } catch (error) {
            // Detaylı hata bilgisi logla
            apiLogger.error('Error in login:', {
                error: error,
                message: error instanceof Error ? error.message : 'Unknown error',
                stack: error instanceof Error ? error.stack : 'No stack trace',
                type: typeof error,
                errorObject: JSON.stringify(error, Object.getOwnPropertyNames(error))
            });

            // Kullanıcıya uygun hata mesajı dön
            const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
            return reply.status(500).send({
                success: 0,
                error: 'Internal server error'
            });
        }
    });

    // Kullanıcı bilgileri getirme
    // Site giriş loglarını tutmak için import

    fastify.get('/users/me', { preHandler: [requireAuth()] }, async (request, reply) => {
        try {
            const user = (request as any).user;
            if (!user) {
                return reply.status(404).send({
                    success: 0,
                    error: 'Kullanıcı bulunamadı'
                });
            }

            const userId = user.id;

            // Global cache'den aktif oturum bilgilerini al
            const globalCache = globalStore.collection("globalCache");
            const users = globalCache.get("users") as Map<number, any>;
            const cachedUserData = Array.from(users.entries()).find(([_, u]) => 
                u.username.toLowerCase() === user.username.toLowerCase()
            );

            // Kullanıcının online durumunu kontrol et
            const stackCollection = globalStore.collection('stack');
            const isOnline = stackCollection.has(user.username.toLowerCase());

            // User flags'i parse et - string/number/bigint olabilir
            const userFlagsBigInt = typeof user.user_flags === 'bigint' ? 
                user.user_flags : 
                typeof user.user_flags === 'string' ? 
                    BigInt(user.user_flags) : 
                    BigInt(user.user_flags || 0);
            
            // maskToFlags fonksiyonu ile yetkileri çözümle
            const permissions = maskToFlags(userFlagsBigInt);

            // Bitflags ve salary değerlerini de BigInt olarak ele al
            const bitflagsBigInt = typeof user.bitflags === 'bigint' ? 
                user.bitflags : 
                typeof user.bitflags === 'string' ? 
                    BigInt(user.bitflags) : 
                    BigInt(user.bitflags || 0);

            const salaryBigInt = typeof user.salary === 'bigint' ? 
                user.salary : 
                typeof user.salary === 'string' ? 
                    BigInt(user.salary) : 
                    BigInt(user.salary || 0);

            let hasCodeName: boolean | undefined = undefined;
            try {
                if (bitflagsManager.hasPermission(bitflagsBigInt.toString(), 'GIVE_BADGES')) {
                    const codenameRow = await getCodename({
                        in: 'id',
                        value: userId,
                        out: 'all'
                    });
                    hasCodeName = !!(codenameRow?.codename && typeof codenameRow.codename === 'string' && codenameRow.codename.trim().length > 0);
                }
            } catch (error) {
                apiLogger.error('Failed to resolve hasCodeName:', error);
            }

            // Ban kontrolü yap (IP ve kullanıcı ID için)
            const { getBanInfo } = await import('../../../db_utilities/ban');
          const requestIp =
  request.headers['cf-connecting-ip']?.toString() ||
  request.headers['x-forwarded-for']?.toString()?.split(',')[0].trim() ||
  request.socket.remoteAddress ||
  '0.0.0.0';
            const banInfo = await getBanInfo(userId, requestIp);

            // Yanıt objesi oluştur
            const response = {
                success: 1,
                user: {
                    id: user.id,
                    username: user.username,
                    habbo_id: user.habbo_id,
                    avatar: user.avatar,
                    badge: user.badge,
                    rank: user.rank,
                    salary: salaryBigInt.toString(),
                    bitflags: bitflagsBigInt.toString(),
                    ...(hasCodeName !== undefined ? { hasCodeName } : {}),
                    // Yapılandırılmış yetki objesi
                    permissions: {
                        ...permissions,
                        raw: userFlagsBigInt.toString() // Raw permission mask'i de ekle
                    },
                    created_at: user.created_at,
                    online: isOnline,
                    current_look: cachedUserData ? cachedUserData[1].look : null,
                    current_motto: cachedUserData ? cachedUserData[1].motto : null,
                    is_banned: !!banInfo
                },
                banned: !!banInfo,
                ban_info: banInfo
            };

            return reply.send(response);

        } catch (error) {
            apiLogger.error('Error in /users/me:', error);
            return reply.status(500).send({
                success: 0,
                error: 'Internal server error'
            });
        }
    });

    // Site aktivitesi WebSocket için token (çerez HttpOnly olduğu için REST ile alınır)
    fastify.get('/users/activity-token', { preHandler: [requireAuth()] }, async (request, reply) => {
        try {
            const { createActivityToken } = await import('../../ws/wsTokenStore');
            const user = (request as any).user;
            const token = createActivityToken(String(user.id), user.username || '');
            return reply.send({ success: 1, token });
        } catch (error) {
            apiLogger.error('Error in /users/activity-token:', error);
            return reply.status(500).send({ success: 0, error: 'Internal server error' });
        }
    });

    // Sitede kaç cihaz/sekmenin açık olduğu (WebSocket bağlantı sayısı)
    fastify.get('/users/active-count', { preHandler: [requireAuth()] }, async (request, reply) => {
        try {
            const { getSiteActivityCount } = await import('../../ws/siteActivity');
            const activeCount = getSiteActivityCount();
            return reply.send({ success: 1, activeCount });
        } catch (error) {
            apiLogger.error('Error in /users/active-count:', error);
            return reply.status(500).send({ success: 0, error: 'Internal server error' });
        }
    });
}